name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload file report files as an artifact
        if: success()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: reports
          path: reports/
          retention-days: 1

  build:
    needs: test
    name: Build, Package and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: Restore node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Prune dependencies for production
        run: npm prune --production

      - name: zip
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd dist
          zip -q -r ${{ github.event.repository.name }}-${{ github.run_number }}.zip .
          cd ../
          zip -q -u -r dist/${{ github.event.repository.name }}-${{ github.run_number }}.zip node_modules package.json

      - name: Configure AWS Credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OPERATIONS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: lambda-github-action

      - name: Release package to S3
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws s3 cp dist/${{ github.event.repository.name }}-${{ github.run_number }}.zip s3://${{ secrets.ARTEFACT_BUCKET }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ github.run_number }}.zip

  sonarcloud:
    needs: test
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download a reports artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: reports
          path: reports

      - name: SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@v1.6
        with:
          projectBaseDir: ${{ env.GITHUB_WORKSPACE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    runs-on: ubuntu-latest
    needs:
      - test
      - build
      - sonarcloud
    steps:
      - name: Workflow Conclusion Action
        uses: technote-space/workflow-conclusion-action@v2.0.1

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          author_name: GitHub Action
          fields: repo,commit,message,author
          mention: channel
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
